package desafio.conquista.setup.itau.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class IniciarView extends JFrame {
    private JPanel Rodape;
    private JLabel Cabecalho;
    private JPanel Painel;
    private JButton IniciarButton;
    private JButton SairButton;

    private JFrame frame;

    public IniciarView(JFrame frame) {
        this.frame = frame;
        addActionListeners();
    }

    public void addActionListeners() {
        IniciarButton.addActionListener(e -> abrirValidacao());
        SairButton.addActionListener(e -> encerrarValidacao());
    }

    private void abrirValidacao() {
        ValidacaoView validacao = new ValidacaoView(frame);
        frame.setContentPane(validacao.getMainPanel());
        frame.revalidate();
        frame.repaint();
        frame.setSize(700, 550);
    }

    private void encerrarValidacao() {
        System.exit(0);
    }


    public JPanel getMainPanel() {
        return Painel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        // $$$setupUI$$$();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Painel = new JPanel();
        Painel.setLayout(new GridLayoutManager(4, 3, new Insets(10, 10, 10, 10), -1, -1));
        Painel.setBackground(new Color(-1977648));
        Font PainelFont = this.$$$getFont$$$("Ubuntu Condensed", Font.BOLD, 25, Painel.getFont());
        if (PainelFont != null) Painel.setFont(PainelFont);
        Cabecalho = new JLabel();
        Font CabecalhoFont = this.$$$getFont$$$("Ubuntu Condensed", Font.BOLD, 25, Cabecalho.getFont());
        if (CabecalhoFont != null) Cabecalho.setFont(CabecalhoFont);
        Cabecalho.setForeground(new Color(-40448));
        Cabecalho.setText("Motor Validador Antifraude");
        Painel.add(Cabecalho, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(283, 27), null, 0, false));
        Rodape = new JPanel();
        Rodape.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        Rodape.setBackground(new Color(-1977648));
        Painel.add(Rodape, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(266, 10), null, 0, false));
        Rodape.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.CENTER, TitledBorder.TOP, null, null));
        IniciarButton = new JButton();
        IniciarButton.setBackground(new Color(-10989987));
        Font IniciarButtonFont = this.$$$getFont$$$("Ubuntu Light", Font.BOLD, 16, IniciarButton.getFont());
        if (IniciarButtonFont != null) IniciarButton.setFont(IniciarButtonFont);
        IniciarButton.setHideActionText(true);
        IniciarButton.setHorizontalTextPosition(0);
        IniciarButton.setText("Iniciar");
        Rodape.add(IniciarButton);
        SairButton = new JButton();
        SairButton.setBackground(new Color(-10989987));
        Font SairButtonFont = this.$$$getFont$$$("Ubuntu Light", Font.BOLD, 16, SairButton.getFont());
        if (SairButtonFont != null) SairButton.setFont(SairButtonFont);
        SairButton.setHideActionText(true);
        SairButton.setHorizontalTextPosition(0);
        SairButton.setText("Sair");
        Rodape.add(SairButton);
        final Spacer spacer1 = new Spacer();
        Painel.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        Painel.add(spacer2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        Painel.add(spacer3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        Painel.add(spacer4, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Painel;
    }

}

